### ISSUE TITLE
Some Bugs/Glitches

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#289]
> Respawn Page Glitch
> Trapdoors Rotation
> Pressure Plate can only step once.
> Iron door don't works with level 

Hope can be fix, especially Respawn Page... Its annoying... 
Thanks everyone who works on IM  :+1:

**Comment by keithkfng** [comment]
All of the bugs in the newest build?

**Comment by EnderKenji** [comment]
yes
Tested.

**Comment by matcracker** [comment]
I'm currently working on trapdoor, I'm searching the correct meta :)

**Comment by OfficialJoey** [comment]
The pressure plates worked great in Jenkins build #33

**Comment by EnderKenji** [comment]
Yes, All the newest bug tht I found..

**Comment by astersx** [comment]
Ya if a player die,  he cant respawn,  he need exit server,  i did /kill aster and i could not respawn :0

**Comment by thebigsmileXD** [comment]
> Doesn't work with level
You mean lever? When placed directly next to it it will work.
Redstone is going to be totally remade

**Comment by matcracker** [comment]
> Pressure Plate can only step once.
Works only wooden pressure the remaining "ore, iron" and stone give this bug.

**Comment by matcracker** [comment]
I think to have fixed the pressure bug, try last build and check for other bugs :)

**Comment by EnderKenji** [comment]
> Trapdoors (Rotation Glitch)
> Iron Trapdoor , When you stand on pressureplate, it keep give out door sound ... weird 
> Wooden Trapdoor can't work with redstone 
> Preesure plate : When we stand on pressure plate a long time, the pressure plate will back to normal, not the press animation. (Hope u knw wht im saying)
>  Button not works with RedstoneLamp
>  Redstone torch not works with iron door.
> Detector Rail : After place , it became powered rail.

Idk the respawn page yet, no test...

**Comment by EnderKenji** [comment]
Respawn Page still not fix.... <<< IMPORTANT >>>

And is Stair registered as solid block?

**Comment by thebigsmileXD** [comment]
MOST OF THESE ARE INVALID

**Comment by thebigsmileXD** [comment]
AND NO STAIR IS NOT SOLID BUT IF YOU WOULD READ THE CODE YOU WOULD KNOW

YOU LET ME RAGE

My internet crashed. Thats why the rails arent fixed, BE HAPPY THAT YOU ATLEAST PLACE SOME OF THEM!
AND NO. BECAUSE OF YOU I WONT WORK ON PLATES ANYMORE. STOP PISSING ME OUT!

**Comment by EnderKenji** [comment]
New Build Bug : PressurePlate Crash Server -.-

PocketMine-MP Crash Dump Mon Dec 14 20:00:22 MST 2015

Error: Class name must be a valid object or a string
File: /src/pocketmine/block/HeavyWeightedPressurePlate
Line: 77
Type: E_ERROR

Code:
[68] 	public function onEntityCollide(Entity $entity){
[69] 		if(!$this->isPowered()){
[70] 			$this->togglePowered();
[71] 			$this->getLevel()->scheduleUpdate($this, 50);
[72] 		}
[73] 	}
[74] 	
[75] 	public function isEntityCollided(Entity $entityallow = null){
[76] 		foreach ($this->getLevel()->getEntities() as $entity){
[77] 			if(($entity instanceof $entityallow || $entityallow === null) && $entity->getPosition() === $this)
[78] 				return true;
[79] 		}
[80] 		return false;
[81] 	}
[82] }
[83] 
[84] 
[85] 
[86] 
[87] 

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux e5-1620v3.1u-phx0.1.141.6.5.32.securedservers.com 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux

**Comment by OfficialJoey** [comment]
Is that ConflictPE's server or yours?

**Comment by EnderKenji** [comment]
CPE

**Comment by OfficialJoey** [comment]
Maybe wait for a new build where it doesn't crash the server? Just don't use pressure plates just yet.

**Comment by EnderKenji** [comment]
and another issue,, Can't Damage others.... /_\ Check pls... im not sure is IM prob,, but it happened after update new build...

omg... getting worst... pls fix...

**Comment by thebigsmileXD** [comment]
Yea, i trued to fix pressure plates late in the night, until midnight. So bugs are normal.

**Comment by EnderKenji** [comment]
Sorry dude,,the Cant damage bug is not IM xD Sorry... ._.

**Comment by thebigsmileXD** [comment]
.-. Ok

**Comment by thebigsmileXD** [comment]
Rails and pressure plates are fixed. Don't wonder that activator rails drop. I just only need to commit

**Comment by EnderKenji** [comment]
Ok, But the mossssssst Important thing u need to fix is RESPAWN PAGE. :3

**Comment by EnderKenji** [comment]
And Yes, I use WorldProtect or iProtect plug,, the stair can be broken... is the stair not registered as a block? I older builds of IM didnt have this  prob... hope fix,, the peeps keep destroy the stairs xD

**Comment by SalmonGER** [comment]
Same. xD

**Comment by thebigsmileXD** [comment]
WE WILL (McpePig is messing up the code.. After his 500 commits in player.php i wouldn't wonder if everything is is messed up.)

**Comment by MCPEPIG** [comment]
@thebigsmileXD Stop blaming eveything on me. Also, the commit you reverted for the pressure plates is NOT invalid. You in fact, CANT place pressure plates on fence gates.

**Comment by MCPEPIG** [comment]
Also, respawn page bug is fixed. I tried with /kill & lava.

**Comment by EnderKenji** [comment]
Not fix.

**Comment by MCPEPIG** [comment]
Are you using the latest build?

**Comment by MCPEPIG** [comment]
Cause I killed myself with /kill, lava, cactus, harming effect, & wither and I got the respawn page and I'm using latest build

**Comment by thebigsmileXD** [comment]
Read the changes in the commit

**Comment by keithkfng** [comment]
Cmon guys... I really want you two to stay together and develop ImagicalMine, but you two just don't seem to get along... I'm gonna have to find a way so one works on one end and to the other works on the another end.

**Comment by EnderKenji** [comment]
Decrease the pressure plate delay time pls..

**Comment by thebigsmileXD** [comment]
Okay.. I'll try to change it to the correct time when other things are fixed. Open a new issue please so i won't forget.

**Comment by EnderKenji** [comment]
Ok

**Comment by EnderKenji** [comment]
Can fix the stair bug?

Peeps can break stairs even is protected (WorldProtect/iProtect)

**Comment by OfficialJoey** [comment]
Has the pressure plate been fixed Kenji?

**Comment by thebigsmileXD** [comment]
They are fixed except for the sounds

**Comment by matcracker** [comment]
@EnderKenjii try last build, now trapdoors work and the stairs bug need to be tested

**Comment by matcracker** [comment]
@EnderKenji *

**Comment by keithkfng** [comment]
@matcracker you know you can edit your comment XD

**Comment by EnderKenji** [comment]
Only WoodenStairs fixed,, others stairs still can be break

Preesure Plate still not fix , it wont reset sometimes after server restart.

Respawn Page still not fix... Please... fix this.... 

And Trapdoor works great ,, but still glitchy...

**Comment by matcracker** [comment]
@keithkfng yes, I know but from phone I can't xD

@EnderKenji Thanks for the test, pressure plates are work in progress but strange for stairs...

**Comment by FienixEC** [comment]
Sorry to bother, this is unrelated..where can i ask unrelated questions to
you guys?

**Comment by keithkfng** [comment]
Do people ever read the README or the contributing guidelines? I'm feeling I write those for nothing...

**Comment by EnderKenji** [comment]
And wht about this?
https://github.com/luca28pet/AdvancedKits/issues/25#event-499828887

Please change it back to normal? .-.

**Comment by keithkfng** [comment]
We will, but don't post multiple issues into one issue :P

**Comment by BlackShadow1** [comment]
trapdoor already bugged when you place it..

**Comment by keithkfng** [comment]
I don't think multiple issues under one issue is very user-friendly for the team. Try splitting them up into smaller issues XD
